
version: '3.5'
services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "gunicorn -b 0.0.0.0:5000 -w 4 src.app:app"
    container_name: backend_container
    image: backend_image
    ports:
      - '5000:5000'

